import createError from "../utils/createError.js";

export const fn = async (req, res, next) => {
  try {
  } catch (error) {
    next(error);
  }
};

export const fn1 = async (req, res, next) => {
  try {
  } catch (error) {
    next(error);
  }
};
